config/routes.rb
Rails.application.routes.draw do
  get 'pockets/index'
  get 'pockets/new'
  get 'pockets/show'
  get 'pockets/edit'
  get 'payments/index'
  get 'payments/new'
  get 'payments/show'
  get 'payments/edit'
  resources :exams
  resources :students
  resources :teachers
  resources :reports
  resources :payments
  resources :pockets
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new #menampilkan form data baru
    @exam = Exam.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @exam = Exam.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    exam = Exam.new(resources_params)
    exam.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to exams_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @exam = Exam.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to exam_path(@exam)

  end
  def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to exams_path
    
end

  def index
    @exams = Exam.all
  end

  private
  def resources_params
      params.require(:exam).permit(:title,:mapel, :duration, :nilai, :status, :level, :student_id )
  end



 
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new #menampilkan form data baru
    @payment = Payment.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @payment = Payment.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    payment = Payment.new(resources_params)
    payment.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to payments_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @payment = Payment.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @payment = Payment.find(params[:id])
    @payment.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to payment_path(@payment)

  end
  def destroy #untuk menghapus data
    @payment = Payment.find(params[:id])
    @payment.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to payments_path
    
end

  def index
    @payments = Payment.all
  end

  private
  def resources_params
      params.require(:payment).permit(:id_transaction, :status, :upload)
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def new #menampilkan form data baru
    @pocket = Pocket.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @pocket = Pocket.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    pocket = Pocket.new(resources_params)
    pocket.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to pockets_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @pocket = Pocket.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @pocket = Pocket.find(params[:id])
    @pocket.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to pocket_path(@pocket)

  end
  def destroy #untuk menghapus data
    @pocket = Pocket.find(params[:id])
    @pocket.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to pockets_path
    
end

  def index
    @pockets = Pocket.all
  end

  private
  def resources_params
      params.require(:pocket).permit(:balance, :student_id, :teacher_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new #menampilkan form data baru
    @report = Report.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @report = Report.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    report = Report.new(resources_params)
    report.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to reports_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @report = Report.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @report = Report.find(params[:id])
    @report.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to report_path(@report)

  end
  def destroy #untuk menghapus data
    @report = Report.find(params[:id])
    @report.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to reports_path
    
end

  def index
    @reports = Report.all
  end

  private
  def resources_params
      params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :tanggal)
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def new #menampilkan form data baru
    @student = Student.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @student = Student.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    student = Student.new(resources_params)
    student.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to students_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @student = Student.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @student = Student.find(params[:id])
    @student.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to student_path(@student)

  end
  def destroy #untuk menghapus data
    @student = Student.find(params[:id])
    @student.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to students_path
    
end

  def index
    @students = Student.all
  end

  private
  def resources_params
      params.require(:student).permit(:name, :username, :age, :kelas, :address, :city, :nik)
  end



  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new #menampilkan form data baru
    @teacher = Teacher.new
  end
  def show #menampikan sebuah data secara detail
    id = params[:id]
    @teacher = Teacher.find id
    #render plain: id
  end

  #untuk memperoses data baru yg dimasukkan di form new
  def create 
    teacher = Teacher.new(resources_params)
    teacher.save
    flash[:notice]= 'Data sudah tersimpan'
    redirect_to teachers_path
  end

  def edit #menampilkan daya yg sudah disimpan di edit
    @teacher = Teacher.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @teacher = Teacher.find(params[:id])
    @teacher.update(resources_params)

    flash[:notice]= 'Data sudah terupdate'
    redirect_to teacher_path(@teacher)

  end
  def destroy #untuk menghapus data
    @teacher = Teacher.find(params[:id])
    @teacher.destroy        

    flash[:notice]= 'Data sudah terhapus'

    redirect_to teachers_path
    
end

  def index
    @teachers = Teacher.all
  end

  private
  def resources_params
      params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>
    
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>


    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    

    <%= f.submit 'Simpan' %>
<% end %>
    

app/views/exams/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_exam_path %>
<table class="table">
    <tr>
        <th>Title</th>

        <th>Mapel</th>
        <th>Duration</th>        
        <th>Nilai</th>
        <th>Status</th>
        <th>Level</th>
        <th>Student_id</th>
    </tr>
    <% @exams.each do |exam| %>
    <tr>
        <td> <%= exam.title %></td>

        <td> <%= exam.mapel %></td>

        <td> <%= exam.duration %></td>

        <td> <%= exam.nilai %></td>

        <td> <%= exam.level %></td>

        <td> <%= exam.student_id %></td>
        <td> <%= link_to 'Detail',exam_path(exam) %> | <%= link_to 'Edit',edit_exam_path(exam) %>|  <%= link_to 'Delete',exam_path(exam) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

    </tr>
    <% end %>
</table>
</body>
</html>

app/views/exams/new.html.erb
<%= form_for(@exam) do |f| %>
    
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>


    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    

    <%= f.submit 'Simpan' %>
<% end %>
    

app/views/exams/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>

<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<table class="table">
<thead>
<tr>
<th>Title</th>
<th>Mapel</th>
<th>Duration</th>        
<th>Nilai</th>
<th>Status</th>
<th>Level</th>
<th>Student_id</th>
</tr>
</thead>
<tbody>
<tr>
<td><%= @exam.mapel %> </td>
<td><%= @exam.duration %> </td>
<td><%= @exam.nilai %> </td>
<td><%= @exam.status %> </td>
<td><%= @exam.level %> </td>
<td><%= @exam.student_id %> </td>


</tr>
</tbody>
</table>
</body>
</html>

app/views/payments/edit.html.erb
<%= form_for(@payment) do |f| %>
    
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    

    <%= f.submit %>
<% end %>
    

app/views/payments/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_payment_path %>
<table class="table">
    <tr>
        <th>ID Transaksi</th>
        <th>Status</th>
        <th>Upload</th>        
        
    </tr>
    <% @payments.each do |payment| %>
    <tr>
        <td> <%= payment.id_transaction %></td>

        <td> <%= payment.status %></td>

        <td> <%= payment.upload %></td>

        <td> <%= link_to 'Detail',payment_path(payment) %> | <%= link_to 'Edit',edit_payment_path(payment) %>|  <%= link_to 'Delete',payment_path(payment) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

        </tr>
    <% end %>
</table>
</body>
</html>

app/views/payments/new.html.erb
<%= form_for(@payment) do |f| %>
    
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    

    <%= f.submit %>
<% end %>
    

app/views/payments/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>

<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<table class="table">
<thead>
<tr>
    <th>ID Transaksi</th>
    <th>Status</th>
    <th>Upload</th>        
    
<tr>
<thead>
<tbody>
<tr>
<td><%= @payment.id_transaction %> </td>
<td><%= @payment.status %> </td>
<td><%= @payment.upload %> </td>

<tr>
</tbody>
</table>
</body>
</html>

app/views/pockets/edit.html.erb
<%= form_for(@pocket) do |f| %>
    
    <%= f.label :balance %> </br>
    <%= f.text_field :balance %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

   
    

    <%= f.submit %>
<% end %>
    

app/views/pockets/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_pocket_path %>
<table class="table">
    <tr>
        <th>Saldo</th>
        <th>ID Student</th>
        <th>ID Teacher</th>
            </tr>
    <% @pockets.each do |pocket| %>
    <tr>
        <td> <%= pocket.title %></td>

        <td> <%= pocket.hasil %></td>

        <td> <%= pocket.mapel %></td>

        <td> <%= pocket.teacher_id %></td>

        <td> <%= pocket.student_id %></td>

        <td> <%= pocket.tanggal %></td>
        <td> <%= link_to 'Detail',pocket_path(pocket) %> | <%= link_to 'Edit',edit_pocket_path(pocket) %>|  <%= link_to 'Delete',pocket_path(pocket) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

        </tr>
    <% end %>
</table>
</body>
</html>

app/views/pockets/new.html.erb
<%= form_for(@pocket) do |f| %>
    
    <%= f.label :saldo %> </br>
    <%= f.text_field :balance %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

   
    

    <%= f.submit %>
<% end %>
    

app/views/pockets/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>

<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<table class="table">
<thead>
<tr>
    <th>Balance</th>
    <th>ID Student</th>
    <th>ID Teacher</th>        
    
</tr>
<thead>
<tbody>
<tr>
<td><%= @pocket.balance %> </td>
<td><%= @pocket.student_id %> </td>
<td><%= @pocket.teacher_id %> </td>

</tr>
</tbody>
</table>
</body>
</html>

app/views/reports/edit.html.erb
<%= form_for(@report) do |f| %>
    
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>


    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :tanggal %> </br>
    <%= f.text_field :tanggal %> </br>

    

    <%= f.submit %>
<% end %>
    

app/views/reports/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_report_path %>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Hasil</th>
        <th>Mapel</th>        
        <th>ID Teacher</th>
        <th>ID Student</th>
        <th>Tanggal</th>
    </tr>
    <% @reports.each do |report| %>
    <tr>
        <td> <%= report.title %></td>

        <td> <%= report.hasil %></td>

        <td> <%= report.mapel %></td>

        <td> <%= report.teacher_id %></td>

        <td> <%= report.student_id %></td>

        <td> <%= report.tanggal %></td>
        <td> <%= link_to 'Detail',report_path(report) %> | <%= link_to 'Edit',edit_report_path(report) %>|  <%= link_to 'Delete',report_path(report) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

        </tr>
    <% end %>
</table>
</body>
</html>

app/views/reports/new.html.erb
<%= form_for(@report) do |f| %>
    
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>


    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :tanggal %> </br>
    <%= f.text_field :tanggal %> </br>

    

    <%= f.submit %>
<% end %>
    

app/views/reports/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>

<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<table class="table">
<thead>
<tr>
    <th>Title</th>
    <th>Hasil</th>
    <th>Mapel</th>        
    <th>ID Teacher</th>
    <th>ID Student</th>
    <th>Tanggal</th>
</tr>
<thead>
<tbody>
<tr>
<td><%= @report.title %> </td>
<td><%= @report.hasil %> </td>
<td><%= @report.mapel %> </td>
<td><%= @report.teacher_id %> </td>
<td><%= @report.student_id %> </td>
<td><%= @report.tanggal %> </td>

</tr>
</tbody>
</table>
</body>
</html>

app/views/students/edit.html.erb
<%= form_for(@student) do |f| %>
    
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>


    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>
    

    <%= f.submit %>
<% end %>
    

app/views/students/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_student_path %>
<table class="table">
    <tr>
        <th>Nama</th>

        <th>Username</th>
        <th>Usia</th>        
        <th>Kelas</th>
        <th>Alamat</th>
        <th>Kota</th>
        <th>NIK</th>
    </tr>
    <% @students.each do |student| %>
    <tr>
        <td> <%= student.name %></td>

        <td> <%= student.username %></td>

        <td> <%= student.age %></td>

        <td> <%= student.kelas %></td>

        <td> <%= student.address %></td>

        <td> <%= student.city %></td>

        <td> <%= student.nik %></td>
        <td> <%= link_to 'Detail',student_path(student) %> | <%= link_to 'Edit',edit_student_path(student) %>|  <%= link_to 'Delete',student_path(student) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

        </tr>
    <% end %>
</table>
</body>
</html>

app/views/students/new.html.erb
<%= form_for(@student) do |f| %>
    
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>


    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>
    

    <%= f.submit %>
<% end %>
    

app/views/students/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>

<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<table class="table">
<thead>
<tr>
<th>Nama</th>
    <th>Username</th>
    <th>Usia</th>        
    <th>Kelas</th>
    <th>Alamat</th>
    <th>Kota</th>
    <th>NIK</th>
</tr>
<thead>
<tbody>
<tr>
<td><%= @student.name %> </td>
<td><%= @student.username %> </td>
<td><%= @student.age %> </td>
<td><%= @student.kelas %> </td>
<td><%= @student.address %> </td>
<td><%= @student.city %> </td>
<td><%= @student.nik %> </td>

</tr>
</tbody>
</table>
</body>
</html>

app/views/teachers/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Gais!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<body>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %> </br>
<%= link_to 'New Data', new_teacher_path %>
<table class="table">
    <tr>
        <th>Nama</th>

        <th>NIK</th>
        <th>Nama</th>        
        <th>Usia</th>
        <th>Kelas</th>
        <th>Mapel</th>
        
    </tr>
    <% @teachers.each do |teacher| %>
    <tr>
        <td> <%= teacher.nik %></td>

        <td> <%= teacher.name %></td>

        <td> <%= teacher.age %></td>

        <td> <%= teacher.kelas %></td>

        <td> <%= teacher.mapel %></td>

        <td> <%= link_to 'Detail',teacher_path(teacher) %> | <%= link_to 'Edit',edit_teacher_path(teacher) %>|  <%= link_to 'Delete',teacher_path(teacher) ,method: :delete, data: {confirm:'areyou sure?'}%></td>

        </tr>
    <% end %>
</table>
</body>
</html>